path:
  - x: 0.0
    y: 0.0
    yaw: 0.0
  - x: 1.0
    y: 0.0
    yaw: 0.0
  - x: 2.0
    y: 0.5
    yaw: 0.1
  - x: 3.0
    y: 1.0
    yaw: 0.2
  - x: 4.0
    y: 1.8
    yaw: 0.3
  - x: 5.0
    y: 3.0
    yaw: 0.5

