
goals:
  - x: 1.0
    y: 1.0
    yaw: 1.5708
    radius_thresh: 0.2
    yaw_thresh_rad: 0.1745
  - x: 2.0
    y: 2.0
    yaw: 0.7854
    radius_thresh: 0.2
    yaw_thresh_rad: 0.1745
  - x: 3.0
    y: 1.0
    yaw: 0.0
    radius_thresh: 0.3
    yaw_thresh_rad: 0.2618
